In [8]:
import librosa
import numpy as np

# Load the speech signal
audio_path = 'C:/Users/LOKESH PAPPU/Desktop/NITW/day 11/Dataset Child/Male/M1_01_01.wav'
signal, sr = librosa.load(audio_path, sr=None)

# Extract MFCC features
mfccs = np.mean(librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=13).T,axis=0)

# Calculate delta features from MFCCs
delta_mfccs = librosa.feature.delta(mfccs)

# Calculate double delta features from MFCCs
double_delta_mfccs = librosa.feature.delta(mfccs, order=2)

In [9]:
mfccs

array([-321.48428  ,  138.27592  ,  -42.382725 ,   44.0637   ,
         29.19823  ,  -39.959347 ,   -5.1629806,  -10.538185 ,
        -27.698563 ,   -3.9156234,  -12.63732  ,  -14.6006   ,
         -1.7011904], dtype=float32)

In [10]:
delta_mfccs

array([ 11.985283 ,  11.985283 ,  11.985283 ,  11.985283 ,  11.985283 ,
       -11.137979 ,  -1.8221463,  -5.1768665,  -0.9307927,  -0.9307927,
        -0.9307927,  -0.9307927,  -0.9307927], dtype=float32)

In [11]:
double_delta_mfccs

array([-19.818893 , -19.818893 , -19.818893 , -19.818893 , -19.818893 ,
         7.3461103,  -0.6705723,   4.4616947,   2.8789737,   2.8789737,
         2.8789737,   2.8789737,   2.8789737], dtype=float32)

In [28]:
import librosa
import numpy as np
import os

# Directory path containing the audio files
directory = 'C:/Users/LOKESH PAPPU/Desktop/NITW/day 11/Dataset Child/Male/'
# Initialize a list to store the features
features_list = []


In [30]:
# Iterate over the files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.wav'):
        # Load the audio signal
        audio_path = os.path.join(directory, filename)
        signal, sr = librosa.load(audio_path, sr=None)

        # Extract MFCC features
        mfccs = np.mean(librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=13).T,axis=0)

        # Calculate delta features from MFCCs
        delta_mfccs = librosa.feature.delta(mfccs)

        # Calculate double delta features from MFCCs
        double_delta_mfccs = librosa.feature.delta(mfccs, order=2)

       

        # Concatenate the renamed features
        features = np.concatenate((mfccs, delta_mfccs, double_delta_mfccs),axis=0)
        # Append the features to the list
        features_list.append(features)


In [36]:
import pandas as pd
df=pd.DataFrame(features_list)
df["gender"]="male"
df["label"]="child"
df.to_csv("Child_Male_delta_Features.csv")

In [39]:
# Directory path containing the audio files
directory = 'C:/Users/LOKESH PAPPU/Desktop/NITW/day 11/Mozilla Dataset Adult/Female/'
# Initialize a list to store the features
features_list = []
# Iterate over the files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.mp3'):
        # Load the audio signal
        audio_path = os.path.join(directory, filename)
        signal, sr = librosa.load(audio_path, sr=None)

        # Extract MFCC features
        mfccs = np.mean(librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=13).T,axis=0)

        # Calculate delta features from MFCCs
        delta_mfccs = librosa.feature.delta(mfccs)

        # Calculate double delta features from MFCCs
        double_delta_mfccs = librosa.feature.delta(mfccs, order=2)

       

        # Concatenate the renamed features
        features = np.concatenate((mfccs, delta_mfccs, double_delta_mfccs),axis=0)
        # Append the features to the list
        features_list.append(features)
import pandas as pd
df=pd.DataFrame(features_list)
df["gender"]="female"
df["label"]="adult"
df.to_csv("Adult_Female_delta_Features.csv")


In [40]:
# Directory path containing the audio files
directory = 'C:/Users/LOKESH PAPPU/Desktop/NITW/day 11/Mozilla Dataset Adult/Male/'
# Initialize a list to store the features
features_list = []
# Iterate over the files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.mp3'):
        # Load the audio signal
        audio_path = os.path.join(directory, filename)
        signal, sr = librosa.load(audio_path, sr=None)

        # Extract MFCC features
        mfccs = np.mean(librosa.feature.mfcc(y=signal, sr=sr, n_mfcc=13).T,axis=0)

        # Calculate delta features from MFCCs
        delta_mfccs = librosa.feature.delta(mfccs)

        # Calculate double delta features from MFCCs
        double_delta_mfccs = librosa.feature.delta(mfccs, order=2)

       

        # Concatenate the renamed features
        features = np.concatenate((mfccs, delta_mfccs, double_delta_mfccs),axis=0)
        # Append the features to the list
        features_list.append(features)
import pandas as pd
df=pd.DataFrame(features_list)
df["gender"]="male"
df["label"]="adult"
df.to_csv("Adult_Male_delta_Features.csv")
